apiVersion: 1

datasources:
  - name: InfluxDB-PDR
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: usth
      defaultBucket: pdr
      tlsSkipVerify: true
    secureJsonData:
      token: usth-sensor-admin-token-change-me
